CREATE TABLE weather_data(
    id SERIAL primary key,
    city text,
    country TEXT,
    longitude float,
    latitude float,
    wind_speed float,
    wind_deg float,
    temperature float,
    category text,
    min_temperature float,
    max_temperature float,
    sea_level int,
    ground_level int,
    humidity int,
    pressure int,
    sunrise TIMESTAMP,
    sunset TIMESTAMP,
    description text,
    collected_at TIMESTAMP
);